--BONUSES
CREATE SCHEMA IF NOT EXISTS bonuses;

--BALANCES
CREATE TABLE IF NOT EXISTS bonuses.bonuses
(
    id SERIAL PRIMARY KEY,
    value NUMERIC(9,2) DEFAULT 0,
    processed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
