--ROLES IMPLEMENTATION
CREATE TABLE IF NOT EXISTS roles
(
    id   SMALLSERIAL PRIMARY KEY,
    value VARCHAR(10) NOT NULL UNIQUE
);

INSERT INTO roles(value)
VALUES ('USER'),
       ('ADMIN');

--USERS IMPLEMENTATION
CREATE TABLE IF NOT EXISTS users
(
    id   SERIAL PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL,
    role_id SMALLINT NOT NULL
);

INSERT INTO users(login, password, role_id)
VALUES ('u1', 'p1', 1);
