--ORDERS STATUS
CREATE TABLE IF NOT EXISTS statuses
(
    id SMALLSERIAL PRIMARY KEY,
    status VARCHAR(15) NOT NULL UNIQUE
);

INSERT INTO statuses(status)
VALUES ('NEW'),
       ('PROCESSING'),
       ('INVALID'),
       ('PROCESSED'),
       ('UNDEFINED');

--ORDERS ITSELF
CREATE TABLE IF NOT EXISTS orders
(
    id SERIAL PRIMARY KEY,
    num NUMERIC NOT NULL UNIQUE,
    status_id SMALLINT REFERENCES statuses(id) NOT NULL,
    user_id INTEGER REFERENCES users(id) NOT NULL,
    bonus_id INTEGER UNIQUE REFERENCES bonuses(id) NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
