CREATE SCHEMA IF NOT EXISTS orders;

--ORDERS STATUS
CREATE TABLE IF NOT EXISTS orders.statuses
(
    id SMALLSERIAL PRIMARY KEY,
    status VARCHAR(15) NOT NULL UNIQUE
);

INSERT INTO orders.statuses(status)
VALUES ('NEW'),
       ('PROCESSING'),
       ('INVALID'),
       ('PROCESSED'),
       ('UNDEFINED');

--ORDERS ITSELF
CREATE TABLE IF NOT EXISTS orders.orders
(
    id SERIAL PRIMARY KEY,
    num NUMERIC NOT NULL UNIQUE,
    status_id SMALLINT REFERENCES orders.statuses(id) NOT NULL,
    user_id INTEGER REFERENCES users.users(id) NOT NULL ,
    accrual_status SMALLINT,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE SCHEMA IF NOT EXISTS users;

--ROLES IMPLEMENTATION
CREATE TABLE IF NOT EXISTS users.roles
(
    id   SMALLSERIAL PRIMARY KEY,
    role_id VARCHAR(10) NOT NULL UNIQUE
);

INSERT INTO users.roles(role_id)
VALUES ('ADMIN'),
       ('USER');

--USERS IMPLEMENTATION
CREATE TABLE IF NOT EXISTS users.users
(
    id   SERIAL PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL,
    role_id SMALLINT NOT NULL
);