// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/erupshis/bonusbridge/internal/bonuses/storage/managers (interfaces: BaseBonusesManager)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	data "github.com/erupshis/bonusbridge/internal/bonuses/data"
	gomock "github.com/golang/mock/gomock"
)

// MockBaseBonusesManager is a mock of BaseBonusesManager interface.
type MockBaseBonusesManager struct {
	ctrl     *gomock.Controller
	recorder *MockBaseBonusesManagerMockRecorder
}

// MockBaseBonusesManagerMockRecorder is the mock recorder for MockBaseBonusesManager.
type MockBaseBonusesManagerMockRecorder struct {
	mock *MockBaseBonusesManager
}

// NewMockBaseBonusesManager creates a new mock instance.
func NewMockBaseBonusesManager(ctrl *gomock.Controller) *MockBaseBonusesManager {
	mock := &MockBaseBonusesManager{ctrl: ctrl}
	mock.recorder = &MockBaseBonusesManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseBonusesManager) EXPECT() *MockBaseBonusesManagerMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockBaseBonusesManager) GetBalance(arg0 context.Context, arg1 bool, arg2 int64) (float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", arg0, arg1, arg2)
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockBaseBonusesManagerMockRecorder) GetBalance(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockBaseBonusesManager)(nil).GetBalance), arg0, arg1, arg2)
}

// GetBalanceDif mocks base method.
func (m *MockBaseBonusesManager) GetBalanceDif(arg0 context.Context, arg1 int64) (float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceDif", arg0, arg1)
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceDif indicates an expected call of GetBalanceDif.
func (mr *MockBaseBonusesManagerMockRecorder) GetBalanceDif(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceDif", reflect.TypeOf((*MockBaseBonusesManager)(nil).GetBalanceDif), arg0, arg1)
}

// GetWithdrawals mocks base method.
func (m *MockBaseBonusesManager) GetWithdrawals(arg0 context.Context, arg1 int64) ([]data.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", arg0, arg1)
	ret0, _ := ret[0].([]data.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockBaseBonusesManagerMockRecorder) GetWithdrawals(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockBaseBonusesManager)(nil).GetWithdrawals), arg0, arg1)
}

// WithdrawBonuses mocks base method.
func (m *MockBaseBonusesManager) WithdrawBonuses(arg0 context.Context, arg1 *data.Withdrawal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawBonuses", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawBonuses indicates an expected call of WithdrawBonuses.
func (mr *MockBaseBonusesManagerMockRecorder) WithdrawBonuses(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawBonuses", reflect.TypeOf((*MockBaseBonusesManager)(nil).WithdrawBonuses), arg0, arg1)
}
